### PR TITLE
added dropbr animation to list

### PR DESCRIPTION
**Pull request by AlbericoD**

### CODE REVIEW

**Comment by reebr** [comment]
Hey @AlbericoD.

#93 was merged and changed the project structure. Here's how to update your PR:
- create a new CSS file inside `./animations` with you animation name, put all your rules there.
- then, add a new object to `./animations.js` with your animation name and your GitHub username.

**Comment by AlbericoD** [comment]
hi @reebr, can you verify that my code is good for the new structure?

**Comment by NiallEccles** [comment]
Hey @AlbericoD Code looks good! I'll merge this.

**Comment by AlbericoD** [comment]
@NiallEccles Thanks it was fun to do that. :smile:

**Pull request merged**
