### PR TITLE
Added background image (pattern) and animation effect.

### PR DESCRIPTION
**Pull request by adsingh14**
Fixed indentation of several files.

### CODE REVIEW

**Comment by adsingh14** [comment]
Hey @NiallEccles ! 

It'd be great if you'll deploy this project via **Github pages.**

**Comment by NiallEccles** [comment]
Hey @adsingh14 this project is already deployed via Github pages.

**Comment by adsingh14** [comment]
@NiallEccles I meant to add it in `README.md` to easily access that link. 🙂

**Comment by NiallEccles** [comment]
@adsingh14 Good point. It is in the project description area at the top of the repo but it may not be obvious to those on mobile. I will add it to the README also.

**Comment by adsingh14** [comment]
@NiallEccles I've already made a PR for this. 
- https://github.com/adsingh14/Hacktoberfest-animations/pull/1

**Comment by NiallEccles** [comment]
That is a pull request in your fork. Could you submit the pull request to this repo?

**Pull request merged**
