### PR TITLE
Wobble animations

### PR DESCRIPTION
**Pull request by lingeshwaran05**

### CODE REVIEW

**Review by NiallEccles — CHANGES_REQUESTED** [review]
Hey 👋 Thanks for making this PR.

I noticed a lot of your classes and animations have a `hvr` prefix. This doesn't match the animation names you've supplied in the`animations.js` file so the animations don't play.

Could you update your animation and class names to not have the `hvr` prefix?

**Comment by lingeshwaran05** [comment]
changes updated #458

**Comment by NiallEccles** [comment]
Nice thanks for making those changes.
 
It also looks like there's an issue with the file name used and the class name. For example, you used `wobble_bottom` in `animations.js` and the file name but then used `wobble-bottom` as the CSS class name.

The code uses the name in `animations.js` to apply a class to the h1. So for your animation to work you would need to update anywhere you used a dash instead of an underscore. 

.wobble-bottom -> wobble_bottom
.wobble-bottom-right -> wobble_bottom_right
.wobble-horizontal -> wobble_horizontal
.wobble-top -> wobble_top
.wobble-top-right -> wobble_top_right
.wobble-vertical -> wobble_vertical

**Comment by NiallEccles** [comment]
One last thing! I noticed you used `display: inline-block` a lot. This makes it so the text and the select element are side-by-side. Is this intended?

**Comment by NiallEccles** [comment]
Nice! Thanks for making those changes 👏

**Comment by lingeshwaran05** [comment]
Thanks for the opportunity 🤝

**Pull request merged**
