### PR TITLE
Hinge Animation

### PR DESCRIPTION
**Pull request by fernandosutter**

### CODE REVIEW

**Comment by reebr** [comment]
Tudo por uma camiseta hein?! Pensei até que fosse o [`pivot.css`](https://github.com/NiallEccles/Hacktoberfest-animations/blob/master/animations/pivot.css).

**Comment by fernandosutter** [comment]
Wow, nem tinha visto que tava duplicado. Acabei de criar o PR #120 para resolver isso.

Obrigado por avisar.

**Comment by hoehooiyan** [comment]
The "hinge-animation" css file is deleted? 
But the animation name is still in the animation.js file?

**Comment by reebr** [comment]
@hoehooiyan can you submit a PR to remove it? 😺

**Comment by hoehooiyan** [comment]
#142 Here it is ✔

**Comment by reebr** [comment]
@hoehooiyan thank you. 😸

**Pull request merged**
