### PR TITLE
(add) Double Border Animation

### PR DESCRIPTION
**Pull request by lovetyagi-17**

### CODE REVIEW

**Comment by NiallEccles** [comment]
Hey there 👋 Thanks for submitting this pull request. Before I merge it, can I ask you to change the name of your animation to something more unique? Thanks.

**Comment by lovetyagi-17** [comment]
Yes you can change it.
But please make me aware with updation of name.

love tyagi

**Comment by NiallEccles** [comment]
I will update it to be doubleBorder

**Comment by lovetyagi-17** [comment]
Ok update it.
And merge it.

love tyagi

**Comment by lovetyagi-17** [comment]
Thanx for all updation and that much wonderful repo and for accepting or
merging my request.

love tyagi

**Pull request merged**
