### PR TITLE
Separating animations into distinct files

### PR DESCRIPTION
**Pull request by reebr**
# What does this pull request do?
In this pull request, a specific directory for animations was created. Thus, each animation will have a specific file, rather than keeping all animations in a single file. I know it's not performance at all, but I believe it is simpler to keep the animations each in one file.

# Why is that?
- Organization, 🧹.
- Avoid problems with identically named classes overwriting rules on the Cascade sheet (see the  explanation below).

# What's been done?
- Removed the `animations.css` file.
- A specific directory for animation CSS files was created.
- Files that have no relation to animations (those that only stylize the page) have been moved to the   `./assets/` directory.
- Edited `script.js` to load animations from `./animations` folder and sort by animation name.
- Update "how to contribute" section on README.md and CONTRIBUTING.md.

# Problems encountered during development
- There were animations using the same class. Example: two different users created the `swing` animation. Following the cascade, the last rule in `animations.css` override the first one. To work around this, classes with duplicate names have been renamed using the following pattern: `<animation_name>-by-<github_username>`. Example: `swing` and `swing-by-jubileu`.
- The animation `color_changes` just have the `@keyframes`. It does not have a specific class, maybe it was removed in some previous commit. @rishabhp99 maybe you want to add it again.
- The `fadeInLeft` animation does not exist in `animation.css`, maybe it was removed in some previous commit (so I don't create a new file inside `./animations` folder). @chisom5 maybe you want to add it again.
- I've removed @Xhika from `<select>` since the animation `boogie` was created by @jdsteinbach ( ref: #87 ) -- the PR does not include any new animation, sorry 😞 .
- The users names were not displayed correctly when found more than one  "-" in the value of the select, now it's fixed:
Actual
image
Fix
image

### CODE REVIEW

**Comment by chisom5** [comment]
i was told to remove it, that there was conflict, that i should just add only the html file without the css class

**Comment by chisom5** [comment]
but i will add it now and commit again

**Comment by chisom5** [comment]
please do i have to create another pull request for it?

**Comment by reebr** [comment]
@chisom5 

> i was told to remove it, that there was conflict, that i should just add only the html file without the css class

Why? You can send your animation with that name, but using another CSS class to differentiate from what already exists, no problem.

> please do i have to create another pull request for it?

Unfortunately yes.

I'll wait your pull request be merged for change mine to ready for review. 🤗

**Comment by NiallEccles** [comment]
> i was told to remove it, that there was conflict, that i should just add only the html file without the css class

Hey @chisom5 sorry, I don't think I explained myself correctly. I asked you to re-submit the pull request just with your animation added and option element in the HTML - [see here](https://github.com/NiallEccles/Hacktoberfest-animations/pull/77#pullrequestreview-296993131) This would included the class on the element as well as the link to your Github. I asked this because there had been some linting and formatting to the code which made it really had to find out what had been changed.

**Comment by NiallEccles** [comment]
> ✋ This is a working in progress (because I'm merging new updates to this repository inside my branch).
> # What does this pull request do?
> 
> In this pull request, a specific directory for animations was created. Thus, each animation will have a specific file, rather than keeping all animations in a single file. I know it's not performance at all, but I believe it is simpler to keep the animations each in one file.
> # Why is that?
> 
> -Organization, 🧹.
> -Avoid problems with identically named classes overwriting rules on the Cascade sheet.
> # What's been done?
> 
>     * A specific directory for the animation CSS files was created.
> 
>     * Files that have no relation to animations (those that only stylize the page) have been moved to the   `./assets/` directory.
> 
>     * Edit `script.js` to load animations from `./animations` folder and sort by animation name.
> 
>     * Update "how to contribute" section on README.
> 
> 
> # Problems encountered during development
> 
>     * There were animations using the same class. Example: two different users created the `swing` animation. Following the cascade, the last rule in `animations. css` override the first one. To work around this, classes with duplicate names have been renamed using the following pattern: `<animation_name>-by-<github_username>`. Example: `swing` and `swing-by-jubileu`.
> 
>     * The animation `color_changes` just have the `@keyframes`. It does not have a specific class, maybe it was removed in some previous commit. @rishabhp99 maybe you want to add it again.
> 
>     * The `fadeInLeft` animation does not exist in `animation.css`, maybe it was removed in some previous commit (so I don't create a new file inside `./animations` folder). @chisom5 maybe you want to add it again.
> 
>     * The users names were not displayed correctly when found more than one  "-" in the value of the select, now it's fixed:
>       Actual
>       image
>       Fix
>       image

This is amazing work @reebr 

Due to the number of changes made regarding structure etc, I will take a bit longer to review this pull request. 

I'm testing it locally on my machine but the animations don't see to be playing. Every time I select a new animation from the dropdown nothing happens. Does it need to be served using liveserver?

**Comment by reebr** [comment]
@NiallEccles thank you. I'm working on this PR yet and waiting all the pending pull requests be merged, so I'll resolve the conflicts and change mine to ready for review. This will make it easier for you to analyze all the changes.

> Does it need to be served using liveserver?
Yes! 😄

**Comment by NiallEccles** [comment]
> @NiallEccles thank you. I'm working on this PR yet and waiting all the pending pull requests be merged, so I'll resolve the conflicts and change mine to ready for review. This will make it easier for you to analyze all the changes.
> 
> > Does it need to be served using liveserver?
> 
> Yes! 😄

Cool cool!

I'm not sure if Github Pages has support for something like that. I just copied your fork for testing and tried to view it here - [https://nialleccles.github.io/123456789876543/](https://nialleccles.github.io/123456789876543/) but the animations don't work. 

We could switch over from Github Pages to Netlify as seen here - [https://hungry-bohr-598660.netlify.com/](https://hungry-bohr-598660.netlify.com/)

**Comment by reebr** [comment]
@NiallEccles I didn't know that, I thought GitHub provided this support as well.
I'm going to run some tests here.

You think it's a good move for Netlify? The bad part is going to lose the "github.io" domain.

**Comment by NiallEccles** [comment]
@reebr might be worth it since the changes you've made so far have been stellar and this would be the best way to structure the project going forward. Maybe we both do some more tests and come back if there are any solutions. I'm leaning more towards just switching the hosting to netlify but you never know, we might figure out something.

**Comment by reebr** [comment]
@NiallEccles maybe (maybe!) the problem is the first `/` here: https://github.com/NiallEccles/Hacktoberfest-animations/blob/7444b7cecfcbe54cd763a34f212cf93ff1410754/assets/script.js#L52

**Comment by reebr** [comment]
@NiallEccles fixed, now it's working on GH pages.

**Comment by NiallEccles** [comment]
Excellent work @reebr . I can confirm it is working on Github Pages. The quality of this pull request is fantastic.

**Comment by reebr** [comment]
@NiallEccles thank you.
Sorry for this lot of changes. 😄 

@chisom5 Do you want me to wait for your pull request before making mine ready for review? There were some changes in the project structure and it might affect what you are developing.

**Comment by NiallEccles** [comment]
@reebr might be good if we could get this merged so as to avoid any complications with newer people forking!

**Comment by reebr** [comment]
@NiallEccles removed the WIP status, the PR can be merged.

**Comment by NiallEccles** [comment]
Thank you for this pull request @reebr , I've merged that into master now. I've also added a little surprise to the README.

**Comment by reebr** [comment]
@NiallEccles thanks for the recon. <3

**Pull request merged**
